* 利用房内分流治疗急性与慢性左心衰竭

房内分流作为针对高压左心房进行减压的新治疗手段，应用在急性或慢性的左心衰竭治疗。
当前研究数据展示了房内分流具有安全性，对于那些对药物与各类治料手段表现出耐受性的症状上也看到了初步疗效。
本文将针对不同情况心衰的治疗手段进行概述、给出临床观点、强调潜在的挑战以及讨论未来治疗的方向。

尽管过去30年里对于心衰管理方面有着许多关键的进展，依旧存在如下问题，高概率引发致命后遗症，低品质的术后生活以及高昂的治疗费用。
并且这些接受过治疗的患者还可能继续恶化，高概率的再次入院甚至死亡。
近期欧州心脏病学界对于心衰方面的研究显示，住院的心衰患者与非住院的心衰患者的12个月内的全因死亡率分别为17%和7%，而其再住院率分别为44%与32%。
值得注意的是，患者左心房（LA）压力升高指征往往会先于左心室的功能阻碍引发的相关症状恶化以及急性失代偿性心衰。
65岁以上的住院病人当中很大一部分是由于急性性心衰症状导致的，其中4-12%的患者表现出心源性休克（非常严重的情况，伴随着高死亡率）。

利用房内分流治疗手段对急性或者慢性心衰患者的左心房进行减压可以对患者的临床情况进行改善。
本文将针对不同情况心衰的治疗手段进行概述、给出临床观点、强调潜在的挑战以及讨论未来治疗的方向。

** 利用房内分流治疗急性左心衰竭

心源性休克管理包括了心血管复苏，发现以及治疗潜在的病因。
血管活性剂（Vasoactive Agents）可以保持心脏的血液输出量，但是会增加心肌（Myocardial）的氧气需求量，从而引发心肌缺血（Ischaemia）并增加心率不齐（Arrhythmias）的风险
机械循环支持（Mechanical Circulatory Support, MCS）可以改善心脏的向前流动（improve forward flow）并且治疗炎症，防止由于休克而产生的器官损伤。
静脉－动脉体外循环（Veno-arterial extracorporeal membrane oxygenation, VA-ECMO）被认为是治疗顽固性心源性休克最有效果的治疗手段。
尽管如此，体外循环治疗需要对动脉进行插管，将会增加左心室LV在心脏收缩时泵血的压力值，增加心脏舒张末期或心脏压缩开始前的左右心室的血容量，增加左心房LA的压力，将会进一步恶化左心室的衰竭（failure）以及顽固性肺水肿（refractory pulmonary oedema）。
主动脉内球囊泵被认为是降低左心室压力的常见治疗手段，但是该手段时候并不能提高生存率。
近期心房隔膜造口术（ Atrial septostomy,  AS）被认为是针对由VA-ECMO引发而导致的成年人的并发症进行左心室LV减压的治疗手段，包括顽固性肺水肿以及上半身低氧血症。

*** 临床结果

当前全球范围内，针对已经使用VA-ECMO治疗手段的患者进行心房隔膜造口术AS的系列研究和临床例子还很少。
截止目前为止，患上心源性休克并已经使用了VA-ECMO治疗的患者当中接受了AS手术的患者情况如表格1所示。
表格当中还首次展示了高左心房\室压力或者顽固肺水肿的儿科患者的在VA-ECMO治疗下的情况。
表格当中血液动力学（Haemodynamic）方面相关数据比较有限，还展示一些非入侵式的检查手段的临床数具数据，例如超声心动图（echocardiography），胸部X光以及呼吸参数（respiratory parameters）。

在针对4名儿科患者的系列研究当中，由超声心动图获得的AS在血液动力学的效果数据表示AS可以迅速使左心房LA大小以及房隔膜之间的多普勒速度数值常规化，迅速提升左心室的功能。
最近的针对15位接受了AS的依赖VA-ECMO支持的患者的系列研究表示，AS可以大幅度的降低氧合指数（吸入的氧与血氧的比例，反应肺功能），并且可以通过放射检查肺部可以发现接受AS治疗的患者的肺水肿情况的好转。
另外，对三位患者进行左心房LA的压力测量发现起压力平均值从29mmHG降到了13mmHG（mmHG 毫米汞柱高度）。
对另外九位接受了AS的成年患者进行放射测量的结果，展示了使用血管蒂宽度（vascular pedicle width，VPW，评估血管内容量状态的定量指标）可以做为测量压力的客观指标。
VPW可以测量左锁骨下的主动脉（subclavian artery exits the aorta）以及穿过右主支气管的上腔静脉的宽度，可以表示心脏的容量过载情况（超过心脏腔室正常工作需要的血容量）。
实施AS之后，可以通过VPW的减少（76.6mm 到 57.9mm）表示心脏容量过载情况得到缓解。
另外，所有进行了AS手术的患者都可以观察到氧合指示的优化，左心房压力减少，其中右心房压力保存不变。

对于有顽固性肺水肿以及上身低氧血症并且依赖VA-ECMO设备儿科以及成年患者，AS手术具有操作相对简单，成功率高的特点。
由于当前的患者的数据较少，对于AS的术后急性反应以及临床恶性情况还无法进行总结。
LA减压通常被认为可以解决肺水肿，气管插管以及短期镇静（LA decompression usually leads to a 
resolution of the pulmonary oedema and a shorter period of sedation 
and invasive ventilation.）。
LA减压还能提升心内膜灌注（提升防止血液逆流的能力），减少心肌耗氧量，有助于左心室功能恢复从而帮助患者移除ECMO。
虽然接受了AS的住院患者的死亡率大约为50%，症状稳定的患者大都通过成功的心脏移植延续了生命。
总之，对于那些已经产生由VA-ECMO设备或者是心源性休克引发了顽固并发症的患者来说，AS是一种姑息性的治疗手段，为左心室功能恢复以及心脏移植争取时间。

*** 技术 Technique

AS的技术步骤开始需要进行标准右心导管插入术，测量心腔压力和心输出量（cardiac output）。
在透视和经食道/心内超声心动图的指示下，在卵圆窝（阔筋膜形成的卵圆形凹陷，位于腹股沟韧带内）的中间区域实施房间隔穿刺，之后使用一个长鞘穿过隔膜到达左心房。
利用坚硬的导丝将一个不合规（non-compliant）的囊体放置于房间隔上，之后将囊体进行扩张。
对于已经进行而VA-ECMO治疗的患者而言， 一个大的囊体（大于10-15mm，小于27mm），例如井上囊体Inoue-Balloon或者perihperal balloon外周球囊，可以造成一个大的心房隔膜缺损，影响血液动力（haemodynamically effective）。

*** Future Perspectives

对于接受VA-ECMO治疗的心源性休克患者通常需要额外的手段对左心房进行减压。虽然没有数据可以对各类的左心房减压治疗策略进行横向对比，但是对比使用外科插管术连接ECMO设备，或者植入例如Impell类型的额外设备都比AS更加的复杂合昂贵。
在超声心动图的指导下对儿科患者进行AS（bedside balloon AS）是可行的，可以避免将这类重症的患者移送到导管室（cath lab）。
对于成人患者来说，AS被认为是一种简单的，有可能成为治疗左心膨涨（left heart 
distension）的最优手段之一。
据作者所知，目前上没有在心源性休克以及VA-ECMO背景下对AS的有效性进行前瞻性的研究。


** 利用房内分流治疗慢性左心衰竭

收缩性心衰（无法将足够的血液泵出心脏，HFrEF）和舒张性心衰（无法将足够的血液吸入心脏，HFpEF）连续成为美国最主要的公共健康问题，每年花费超过300亿美元。基于每年90万心衰患者的入院数据，美国全国性的健康与营养研究调查估计美国目前有650万20岁以上的心衰患者。预计到2030年，美国将会有800万的18岁以上的心衰患者，涨幅约为50%。
尽管在医疗和设备治疗方面取得了几十年的重大进展，心衰的发病率和死亡率仍然很高。

左心房压力升高导致的肺动脉充血是诱发慢性心衰患者症状恶化和急性失代偿的常见病因。
运动期间肺毛细血管楔压(PCWP)升高将会导至体能降低，对生活质量和术后（prognosis）产生负面影响。
利用可植入式的血液动力压力监测进行定剂量的药物定滴控制收缩性心衰与舒张性心衰的心房压力，减少心衰患者的住院率以及缓解临床症状。
由于大部分的心衰患者式老人，并且存在还患有当中其他病症，这类复杂的情况对基于设备的治疗方案以及后续治疗带来挑战。

心房分流可以按需自动对通过在左右心房之间进行压力调节，来缓解心房的容量过盛。
在房间隔缺损闭合的患者中观察到左心室压力依从性降低和左心室急性升高的症状，都将会引起肺水肿。
从左到右的心房隔膜造口可能会造成潜在的右心室的容量过载和肺动脉的压力(PAP)升高。
然而，针对先天性缺陷的长期随访研究表明小的破口造成的分流（心房隔膜缺损的大小<10mm）与任何血流动力学上的伤害无关。
因此，一些装置已经被开发出来，帮助心衰患者永久的实现可控制的心房左到右的分流。


*** Devices and Clinical Evidence
*** Inter Atrial Shunt Device 心房分流器

心房分流装置（IASD）由一个中空的镍钛合金圆盘状网格构成，具有多腿状分枝以及防辐射的表记物（radiopaque markers）。圆盘的直径以及开口的直径分别为19mm以及8mm。

对舒张性心衰的患者的IASD术后评估结果情况如下：
对11位被纽约心脏协会NYHA分级标准三级或者四级（LVEF左心室收缩数值>45%）的心衰患者实施IASD设备的放置手术在一开始全部都成功进行了放置，其中有一例一开始进行放置的时候就出现偏差，医生们很快的将其取出，第二次放置之后成功。
对实施IASD植入的后续观察当中，可以发现肺毛细血管楔压(PCWP)的大幅降低30%，右心房压力与肺动脉压力保持稳定。
在30天的随访当中，上述的情况改善了患者6分钟的行走测试，保障了有质量的术后生活以及纽约心脏协会的分级等级评定优化。

多所研究中心对于64名接受了IASD二类系统植入手术的心衰患者，进行了左心房减压相关的实验（REDUCE LAP-HF），其中64名患者为NYHA 2级到4级患者（LVEF 左心室收缩数值>40%）。
装置成功植入所有患者，无重大手术期并发症。
经过6个月的随访，在患者的休息时候进行的右侧插管显示肺毛细血管楔压PCWP数值没有明显的减少，在运动情况下尖峰时刻可以观察到PCWP值大幅降低（平均减少了3mmHg）。
随访观察到该项设备对于患者并没有任何的安全性问题，患者NYHA的评级减轻，有质量的术后生活以及运动能力的提升。
Kaye的一年随访研究表明上述的情况提升可以至少持续1年。
在64位患者当中的48例可以通过经胸超声心动图(TTE)观察到明显的分流情况，无闭塞/狭窄的迹象。
在16例患者（25%）中，认为TTE图像不足以评估分流的通畅度，表明了TTE对心房分流情况检测的潜在风险。
最近，Kaye等人的2年随访研究确定了IASD植入对患者死亡率的潜在影响。
接受ISAD的患者的死亡率为9.4%，与慢性心衰预后模型的预测死亡率进行对比后，表示心房分流治疗减少了33%的全因死亡率。
接受ISAD患者的死亡率与其是否住院对于随后的死亡率增加无关。

Reduce LAP-HF 研究是一项随机试验，包括LVEF>40%和NYHA分级标准3-4类患者。
44位患者接受了IASD二类系统的植入手术，而对照组接受了一个虚假的植入流程（实验组对照组为1：1）。
1个月的随访监测当中，休息时候两组的肺毛细血管楔压(PCWP)没有明显的变化，但是在运动的时候实验组的PCWP数值有了减少。
在1个月和1年随访检测数据当中，两组的功能状态和运动能力均相似。
在1年随访中，IASD组表现出低的住院率，有着向NYHA更加好的等级改善的趋势。
与对照组相比，IASD组在6个月时观察到轻度右心室(RV)扩张，扩张程度到1年的时候没有变化。
随着时间的推移，右心室功能没有下降，也没有分流狭窄/闭塞的迹象。
最后，两组之间的主要心脑血管或肾不良的发生情况也类似，12个月时生存率为95%（每组1例死亡）。

Danial等人的研究表明了心房间分流对右心脏参数存在潜在影响。对22只小白鼠(11只正常 11只收缩性心衰)进行2mm的气囊植入的心房分流实验观察到了收缩性心衰的小白鼠出现左心房的容量减少以及肺动脉直径的减少的现象。
然而，在健康大鼠中，心房分流与右心室超载和肺动脉直径增加有关。
尚需要长期的临床数据来证明心房间分流器对右心室功能存在潜在的影响。

*** V-Wave Device

V-Wave装置是一种沙漏形装置，由硝醇和膨胀的聚四氟乙烯封装，三个猪心包小叶和丙烯缝合线一起缝合，以确保从左到右单向分流。
V-Wave装置的管腔直径为5mm，其治疗情况已经在收缩性心衰患者和舒张性心衰患者中进行了测试。该设备与上一代的装置类似，只是没有瓣叶。
经过最初的人类实验后，这种新一代设备将用于收缩性心衰和舒张性心衰患者的大型随机试验。

V-Wave装置是第一个植入收缩性心衰患者的心房间分流装置。
DelTrigo等人公开了基于10例收缩性心衰患者(平均LVEF25%)和NYHA分类III/IV患者治疗经验，基于最佳的药物与设备治疗的情况。
所有患者都植入了V－Wave设备，在三个月的随访实验当中检测到了PCWP数值的降低（平均5mmHg），右心房压力与肺动脉压力保持稳定。
三个月随访实验当中，根据堪萨斯城心肌病问卷结果表示大部分的患者的基于NYHA的评级提升到了第一级或者第二级，大幅度提升生活质量，在6分钟的行走测试当中大约增加了75m的行走距离

近期关于V-Wave设备的多研究中心的联合研究结果发表了。研究组包括38例病人（其中收缩性心衰患者30人，舒张性心衰患者8人），NYHY的评级为3-4级，全部都是基于最好的药物以及设备治疗的。
所有的患者都成功的植入了设备，只有一例的植入的手术的难度比较高（心包填塞与心包穿刺术）。
截至一年期的随访没有发生额外的设备操作相关的问题。
在术后的前3个月内观察到功能状态、运动能力和生活质量的显著改善，并在1年随访时维持
1年随访结果显示，静止时候的血流动力学参数无变化，包括PCWP、RAP和PAP。
在平均28个月（21-31个月）随访后，10例患者（26%）死亡（8例因心血管原因死亡）,其中一名患者在15个月时接受了左心室辅助装置作为最终治疗，另一名患者在27个月时接受了心脏移植。

在设备植入1-3个月以及1年之后的两个时间点，通过经食管超声心动图评估静脉的通畅度。
所有分流情况可以在1-3个月时完全被观测到，但在1年随访中，14%的患者观察到分流闭塞。
此外，36%的患者在瓣膜上出现了一定程度的分流狭窄，导致1年随访时分流狭窄或闭塞的发生率为50%。
任何患者均未检测到血栓（经超声心动图评估）。
有趣的是，两年后发生狭窄或闭塞的潜在原因是在心脏移植过程中发生的分流闭塞。
生物瓣叶增厚，狭窄，伴有新心内膜增生（胰腺）。
上述数据并且缺乏血栓的情况，表明了分流术内瓣膜恶化是分流狭窄-闭塞的主要病因。
经过了上述的实验对设备进行优化(移除了瓣膜)，优化了设备延迟以及持续有效性。
在11只绵羊的动物实验当中，5-6个月随访时无瓣v-Wave分流保持明显可被观察，并且管腔直径没有后期损失（V-Wave，未发表的数据）。
此外，在一年随访过程中，第一次的人类实验当中使用无瓣v-wave的所有病例的分流都很通畅（无狭窄闭塞）。

在最初v-wave实验当中，一半的心房分流器要发生狭窄或发生了闭塞，对这些发生闭塞以及那些没有发生闭塞的病例进行了对比研究。
那些没有发生闭塞的患者中，随访显示其血液动力学指征数据对比比发生了闭塞的患者有着明显的提升，例如PWCP数值。
此外，在三年随访监测结果表示，被观察到明显分流的患者改善了晚期的临床症状，有着较低的死亡率，左心房辅助治疗发生率，心脏移植发生率以及心衰患者再次住院的几率。
值得注意的是，Kaplan-Meier curve显示，在一年的随访过程中无闭塞组与狭窄闭塞分组死亡率与住院率都相对的相似，在第三年的时候两组的死亡率与住院率的差别才显现出来。
在探索性分析中，V-Wave最初实验的的患者组（年纪大，有着出高风险的身体情况），在3年随访中的临床结果似乎好于心脏传感器监测的NYHA 3级心衰患者（冠军）试验中观察到的结果，原始V－Wave患者组与NYHA 3级程度患者具有相似的入选标准以及患者特征，特别是一年随访中显现出明显的心房分流的患者。

*** Atrial Flow Regulator 心房流量调节器

心房流量调节器（AFR，Occlutech）是由氮醇丝网和中央孔构成的双盘装置。
开窗直径从4到10mm不等，有三个腰围大小：2、5和10mm，以适应房间隔的不同厚度。
AFR装置正在收缩性和舒张性心衰患者中进行测试，目前正在进行的临床试验评估设备安全性和有效性。

综上所述，到目前为止，尽管绝对楔形压力值比基线略有降低，所有的测试设备都被证明是安全的，患者的心脏功能等级和生活质量都有所改善。

*** Technique

对于大多心房分流设备，植入手术是通过经股静脉麻醉或经股静脉麻醉进行的。
经中隔穿刺后，将鞘（14-16Fr）插入左心房腔，使用专用输送系统部署装置。
最初装置的左侧是打开状态，整个设备被往回拉紧（pulled back），确保设备在心房隔膜上进行固定（back tenting）。
接着部署设备的右侧部分，之后整个设备的植入就完成了。

在植入装之后，大部分的研究都建议给未接受抗凝治疗的患者，持续六个月服用阿司匹林与氯吡格雷等相关药物。
对于接受抗凝剂（华法林或直接口服抗凝剂）的患者中，阿司匹林被加入到抗血栓治疗疗程当中。

*** Future Study

心衰患者心房分流研究见补充材料表1。
关于IASD的几项研究目前正处于招募患者阶段。
REDUCE LAP-HFrEF试验(NCT03093961)正在招募NYHA 3-4类压缩性心衰患者，以评估该装置在该特定人群中的安全性和可行性。

另一项涉及IASD以及REDUCE LAP-HF的项随机对照试验，针对LVEF>40%的患者进行，对照组进行最优的常规治疗并进行一个假的植入手术。
预估的样本量包括608例患者，统计其12月内的心血管时间死亡发生率以及首次非致命性缺血性中风的发生时间；
12个月内患者由于心衰导致4级多尿( IV diuresis 
for HF)而入院或医疗机构就诊比例，以及首次心衰发生的时间；
12月后的基于KCCQ（Kansas城市心肌调查问卷的）评分基准线进行评分。
REDUCE LAP-HF III(NCT03191656)计划招募100名LVEF稳定或轻度减少的患者，目的是在12个月的随访中确定该治疗的益处（功能状态、生活质量）。

降低晚期心力衰竭的肺拥堵症状(RELIEVE-HF，NCT03499236)是一项随机对照试验，
实验有500例压缩性或舒张性心衰患者参与，实验组使用第二代（无瓣）V-Wave设备，对照组采用最佳医学治疗（采用假手术）进行比较。
实验的目标是获得分层级的死亡，心脏移植，左心室辅助设备的植入，心衰住院情况，以及六分钟的行走测试的变化情况，随访将会从12月开始24个月结束。

** 结论

心房分流已成为治疗心衰患者的一个很有前景的治疗选择。
对于急性的心衰患者，贴别是那些在VA-ECMO治疗当中患上顽固性肺水肿的患者来说，球囊扩张心房隔膜造口是可行的和有效的。
目前为止，针对慢性的心衰患者（压缩性心衰以及舒张性心衰）目前的使用心房分流的临床病例小于200例，使用的不同的心房分流设备，对于那些有症状的患者被证实是可行以及有效的（这些患者都接受了最优的治疗）。
如果未来以及正在进行的随机实验可以证明心房分流可以优化临床的治疗结果，那么由设备介导的心脏分流将会成为治疗顽固性心衰的重要的新治疗手段。

