* Patent Foramen Ovale Closure: State of Art 未闭 卵圆孔 闭合术：最新情况

Paten foramen ovale（胚胎期不需要使用肺来获得氧气，血将会通过卵圆孔从右心流到左心之后泵到全身，出生之后由于左心的压力正常情况下卵圆孔将会慢慢闭合） （PFO，卵圆孔未闭）是20%－34%成年人口中常发的abnormality缺陷。
对于大部分的人来说，是温和的缺陷病，但是对于一些人来说PFO的开口过大，会造成异常的血栓经血液循环从静脉移动到动脉，会导致中风以及全身性的血栓。对于病因不明中风的患者，经皮的卵圆孔开口闭合术已经被实施多年了。并且多种专用的隔膜闭塞器也已经上市。
近期的随机控制实验表明对于病因不明中风患者进行卵圆孔闭合手术，有助于减少复发性的中风发生几率。
通过对PFO进行整体的分析，本文将会探讨未闭卵圆孔闭合对于隐性中风患者的判定方法。
本会还会给出卵圆孔闭合的一些潜在适应症，包括全身动脉栓塞、减压病(decompression sickness)、正耳痛(platypnoea–orthodeoxia)综合征和先兆偏头痛。
本文阐述了术前前调查和手术准备工作。最后，本文对闭合术过程本身进行了概述，包括对封闭装置的讨论。


Paten foramen ovale PFO 是20%－34%成年人口中常发的abnormality缺陷。
对于大部分的初生幼儿来说，由于肺部动脉的压力减少导致左心房的压力高于右心房，在出生后不久之后婴儿开始呼吸，很快这个卵圆孔将会闭合。
但是对于一部分的人来说，原发孔隔和继发孔隔(属于心肌的褶皱，位于卵圆孔的下方和上方)并没有完全融合。
在胸腔的压力发生突然升高或者降低的时候，例如打喷嚏，咳嗽，用力排便等情况，左右心房会产生一个短暂的暂时性的血液流动。
通过咽鼓管充气检查法可以检测出是否PFO患者会出现由于压力变化而导致卵圆孔暂时打开。

对于大部分成年人来说，PFO只会在心脏调查中被偶然发现，或者更多的情况是都没有被检查出来。
一些PFO可能开口很大，为血栓、空气或血管活性肽从静脉到动脉循环提供一个通路（右心房到左心房）从而引发血栓。
这种异常的静脉动脉的血液转移转移会导致一些临床性的疾病，包括低温源性中风、全身栓塞、先兆偏头痛和潜水员的减压病。
经皮PFO闭合术（从腹股沟的静脉插入，导管进入右心房然后封闭未闭卵圆孔）提供了一个实用和优雅的解决PFO问题的治疗方案。
本综述评估了PFO关闭判定方法，讨论了应考虑哪些患者进行该治疗，并回顾了应如何进行该手术。

** 分析 PFO

随着胚胎的生长，原发孔隔和继发孔隔(属于心肌的褶皱，位于卵圆孔的下方和上方)生长并重叠。出生时候这个PFO开孔应该闭合。
但是PFO患者的心房隔膜没有正常的生成，导致这个隔膜上的卵圆孔小控并没有关闭。
PFO是左右心房的开孔没有关闭，而ASD（心房隔膜缺陷）是同一测的心房与心室之间的隔膜缺陷，需要区分开来，他们有着不同的功能性影响，以及不同的判断方法。

尽管PFO与ASD不同，但是他们都可能导致反常的血栓转移（血管到动脉的血栓）。
通常只有在右心房压力超过左心房压力时，PFO患者的相互重叠原发孔隔以及继发孔隔才会打开。
因为右心房压力通常小于左心房压力，PFO的隔孔通常情况下是机能上关闭的（实际不是真关闭，两个隔膜孔的心肌褶重叠导致的关闭）。
通过改变胸腔的压力（例如打喷嚏，咳嗽，用力排便）可以反转左右心房的压力，导至PFO打开，导至血液，血栓以及其他的物质可以通过这个孔从右心房来到左心房

** 需要进行PFO闭合手术的判断标准

*** 病因不明的中风

尽管有着广泛的调查研究，中风的明确病因往往不能被定位。病因通常可以被认为是房性纤颤(Atrial fibrillation)，动脉粥样，颈动脉夹层以及颅内异常（例如颅内出血，颅内占位性异常）。
40%的中风患者的病因都是无法被确定的。
这些被命名为病因不明的中风。
在患有PFO的患者当中，他的中风原因通常被归结为反向血栓(从血管到动脉的血栓)。
由于PFO患者的中风原因已经找到，称之为无法定为原因的病似乎属于错误的分类，但是由于历史原因，本文还是称之为无法确认病因的中风。
当然也可以称之为栓塞性中风，这个称呼最早是2014年引入的。

1881年Zahn就第一次发现了栓塞性中风。
PFO的开口导致了静脉的血栓移动到了动脉血液循环当中去了，导致了栓塞性中风。
当右心房发生了一个快速的压力升高合降低的时候，给左右心房提供了一个暂时的通道，血栓就有可能会发生转移。
PFO给左右的心房之间提供了一个通道，这个病因被许多研究PFO血栓的研究报告所支持。
在PFO的患者当中，静脉的血栓和原因不明的中风也是有联系的。

最早的关于PFO闭合术的相关随机测试的实验监控目标是，接受STARFlex闭合系统的由反向血栓引发的中风或者是血栓转移的PFO患者以及接受经皮的Amplatza PFO闭合器植入的病因不明的血栓患者，当时的数据和接受最优治疗的最对照组之间没有体现出绝对的治疗性数据优势。
然而，这些研究的设计从一开始就有问题，例如小组划分上的不科学，没有将小组按照PFO引发的或者是错误的使用凝血剂引发血栓这两种不同病因的患者给分在不同的小组。
还有一点是，在闭合实验I当中使用的STARFlex闭塞器可能会引发并发症使血栓在左心房形成，已经由于安全风险在欧洲被禁用了。
上面两个实验的数据更加像是可以推广的一次性的疫苗接种抗凝治疗，而不是长期的抗凝的效果比较。
然后在2014年美国心脏协会和美国中风协会在前两次的测试之前，增加了一个针对PFO的第三期测试。

虽然如此，第三次随机试验从早期的研究中吸取了教训，并证明了PFO闭合术在预防复发性中风方面优于对照组的最优医学治疗。
早期的针对PFO闭合术的复发性的中风评估建立了现行的治疗标准（RESPECT），但是在随访的过程中证实了相比对照组而言，PFO闭合可以减少缺血性血栓的概率。
与单独使用抗血小板的治疗而言，针对PFO中风患者的Gore隔膜闭塞器的使用在临床上答复降低了缺血性血栓的发生率。
高风险PFO（DEFENCSE PFO）两年的随访研究表明，对比对照组的最优的医疗治疗而言，PFO闭合内降低了卒中、血管死亡和心肌梗死大出血溶栓的发生概率。
最后，在PFO闭合实验组与抗凝剂与抗血小板治疗对照组的预防中风复发试验中，PFO组当中没有患者发生了缺血性中风，而对照组出现了14例病例。

对这些试验的分析证实，PFO闭合术可降低PFO和病因未知的中风患者发生缺血性中风的风险。
尽管绝对风险降低较低（每100名患者-年1.0次卒中），但这需要与年轻患者可能面临风险的长期时间进行考量。
房间隔动脉瘤或心房分流较大的患者可获得更大的益处。
接受PFO关闭的患者比单独接受医学治疗的患者更频繁的发生了房性纤颤，然而，这一发现似乎并没有抵消整体中风率的减少的优势。
PFO闭合术预防复发性缺血性卒中的随机试验见表2。

观察数据表明，进行PFO闭合术之后的房颤可能是短暂的，中风风险比其他病因引发的房颤的概率更低。
没有任何试验或观察性研究表明，PFO关闭会降低死亡率，事实上，多个试验分析的结果也没有发现显著的效果。
可能有好处，但如果没有长随访期的大型随机试验，仍很难证明。

参加PFO闭合试验的患者还年轻，很少有研究登记>60岁的患者。
患者年纪越大其反向血栓的绝对风险增加，将老年患者的中风从其他的病因上区分开来也是一件挑战。
患者需要有与中风一致的症状，并通过横截面脑成像确认缺血或梗死。
还需要用经食管超声心动图来确认是否存在PFO。
研究排除了有其他中风原因的患者，并且需要在中风后的6-9个月内注册。

栓塞性中风的主要替代解释之一是房颤，所有患者均需要排除这个病因。
研究表明，从中长期来看，PFO闭合术在美国和英国的医疗保健系统中都是具有成本效益的。
此外，长期的观察性研究表明，PFO闭合术实施的12年后，中风率也非常低（<1%）。

对于研究来说严格标准是很重要的，并且在临床实践中应得到尊重。
在这些标准之外，几乎没有证据表明PFO的治疗对病因无法确定性的中风患者的PFO闭合有益处。
符合试验标准的患者应考虑接受PFO闭合术，而不是常规的医疗治疗。
实验对象患者的选择最好在多学科团队会议上决定，包括神经学/中风医师、植入和成像心脏病专家。

*** Systemic Embolisation 全身性的血栓

因为大脑对缺血非常敏感也受到很大一部分的心输出量的影响，反向血栓(Paradoxical Emboli)可能会导致缺血性中风。
四肢、肠道和冠状动脉下的系统性血栓已经被其他研究者进行过研究。
没有随机试验证据表明，在其他无法解释病因的全身栓塞病例中，PFO闭合术是具有保护性的。
然而，在某些情况下，PFO闭合术似乎是一种合理的策略。
例如，出现栓塞源急性心肌梗死的年轻患者而言，他们中出现一些冠状动脉异常，动脉粥样硬化或房颤的危险因素，关闭PFO是一种合理的选择。
对于这些病例来说治疗的方向和病因不明中风的治疗相似。
非常重要的是需要排除其他病因，这可能需要血管内成像，如光学相干断层扫描，以排除冠状动脉中的斑块破裂，还建议进行心脏核磁共振成像，检测方式与与心肌梗死的病因确认的方式一致。

*** Decompression Illness 减压病

潜水员与高空飞行员这些频繁的在高压与低压环境中切换的人，可能会造成减压病的影响
压力的突然变化会导致氮气泡在组织内形成，并在静脉循环中积累。
这些气泡通过肺部毛细血管扩散，从血液中过滤出去。
但是，如果回到低压（或者对潜水员来说从深度上升）太快，那么肺部的筛选过滤就会难以承受。气泡可进入全身性动脉循环当中.
气泡继续扩大，导致组织创伤，甚至血管阻塞。
症状广泛，从轻度肌肉和关节疼痛、头晕、疲劳、头痛、皮疹和麻醉不良，到严重呼吸困难、精神不清、运动不协调和瘫痪。
一个右心房到左心房的分流通道，例如PFO，会导致这些氮气气泡不经过肺部毛细血管的过滤而直接进入左心房进入动脉循环系统，增加全身性血栓的风险。

潜水概述（Diving profiles）限制了在不同深度的停留之间，以及减缓到水面的上升速度，尽可能的降低减压病的风险。
基于潜水概述的操作下，依旧发生了减压病，这个情况暗示着患者可能出现了右心房到左心房的分流，需要考虑对患者进行ASD或者是PFO的检查。
一项纵向的、非随机的随访研究表明，相比较于那些没有进行PFO闭合的对照组而言，对于患有PFO缺陷或者是减压病的业余潜水者进行PFO闭合减少了他们发展成有症状的神经系统病症和全脑损伤的风险，

最近有一项研究利用经颅脑的多普勒对489名具有PFO缺陷的业余潜水员进行了评估。
该项研究表明，一个大的PFO缺陷孔是发生不明情况的减压疾病的主要原因。
最近的一项研究指出，在59名患有减压疾病和PFO已经闭合的潜水员队列中，有4名在10年的随访期间继续患有减压疾病。
尽管手术已经将PFO进行了闭合，这4名患者被证实是由于残留PFO缺口而导致分流引发的。
如果一个专业的潜水员想要继续的进行潜水，那么推荐他接受PFO闭合手术。
否则建议他放弃潜水或者减少具有挑战性的潜水深度。
如果是业余的潜水员，那么强制性的要求接受PFO闭合手术的建议就是不具备风险和收益分析的价值，接受手术的一定风险也需要与继续潜水的风险进行权衡。

*** Platypnoea–Orthodeoxia Syndrome 直咽综合征 缺氧综合征

直咽综合征是PFO患者当中的一种罕见的疾病，其特征是呼吸困难和身体姿势影响的血氧脱饱和症状。
在一个特定的身体的姿势下，心房隔膜发生几何形改变，可以持续让脱氧合(血红蛋白饱和度低下)的血液持续通过PFO缺口从右心房留如入左心房。
脱氧合通常在病人坐着时出现，但当病人平躺时，氧饱和度正常。
心房隔膜几何变形可能由胸心外科引起，如肺切除术、主动脉扩张和主动脉手术引起，或可能没有可以被确定的病因。

心脏三尖瓣的反流喷射也可以穿过PFO缺口。下腔压力不正常也会影响直咽综合征，只要肺动脉压力不明显升高，PFO闭合可以很好的避免三尖瓣反流。54例病例表明，经皮的PFO闭合术对缺氧综合征是安全有效的。

*** Migraine with Aura 有先兆的偏头痛

偏头痛在年轻人中很常见，它在大约三分之一的病例中是有先兆的。
有先兆的偏头痛被认为是和心房的右到左的分流有关，例如PFO，PFO的缺口越大两者的关系就越明显。
血管活性物质的转移，通常由肺循环过滤到系统循环中，是PFO导致先兆性偏头痛的原因。

一些非随机研究报告了，接受PFO闭合手术的患者症状有所改善。
针对STARFlex对偏头痛的评估实验当中，先兆偏头痛患者随机进行经皮PFO闭合手术或者是一个假手术。
实验组与安慰组之间停止头痛或减少无头痛的日子没有差异。
然而这个实验当中的患者的偏头痛的发生几率本来就比较低，而且进行闭合手术之后，和之前的CLOSURE 1 中风实验相似，在患者的心脏仍然可以发现没有完全闭合PFO产生的心房分流。
这些因素可能导致了负面的结果的产生。

最近，一个关于偏头痛和PFO之间关系的一个新的评估实现也发表了他们的结果，这个评估使用的是Amplatzer PFO闭合设备。
尽管头痛的发生确实有减少，但两个评估实验都得到了与最初的实验目的相悖的负面实验结论。
PFO闭合术产生的治疗效果很有限，而且是以手术并发症作为代价而换取的。
因此得到的评估结果不足以支撑PFO术作为先兆偏头痛治疗的推荐方式。

** PFO闭合术的操作流程

*** 术前调查

FPO闭合通常是位置病因的中风的推荐治疗手段，但是还是需要尝试重新分析中风是否存在其他的可能病因。
应进行横截面脑成像，以确认中风的病因诊断。
常规来说腔隙性脑梗塞不被认为是血栓。

房颤是常见的血栓病因，13%的房颤患者同时患有心脏性血栓。
90%的非瓣膜性房颤患者的血栓位于左心耳。
对于出现房颤的中风患者推荐的治疗手段是抗凝治疗，而不是PFO闭合术。

没有任何研究表明，PFO闭合会带来额外的好处。
需要强制用持续的心电图检测排除房颤，持续的时间取决于患者的危险程度。
我们推荐针对小于50岁的并且没有其他健康风险因素的患者，进行72小时的动态表面心电图记录，
对于大于50岁的患者我们推荐植入循环记录。

植入式循环记录具有扩大节奏监视的优势，然而这样的方法具有假阳或者假阴的可能性。
目前还没有任何的实验结果给出了最优的房颤的判断手段。
动态心电图或心房大小增大导致心室高负荷，增加了发生房颤的可能性，并这些情况表明小于50岁的患者也需要植入式循环记录设备来记录心电图。

颈动脉成像应排除颈动脉斑块疾病。
应考虑对血友病的筛查，但其复杂性质与结果反复意味着通常需要反复进行筛查。
血栓增多通常倾向于静脉血栓形成，而不是动脉血栓形成。
解释病因可能很困难，应该与血液学家一起进行血栓形成的排查。

利用经胸超声心动图排除心内的血栓是第一要务。
除房颤外，许多症状都与心脏血栓有关，心脏血栓可能导致中风。
这些症状包括心肌梗死、左心室动脉瘤、心房肌液瘤、非压实性心肌病、左心室衰竭和二尖瓣狭窄。
在进行PFO闭合术之前，需要排除上述的中风的潜在来源。

研究病因不明的中风患者的一项关键检查手段是通过超声心动图来排除血液中的气泡。
由于PFO导致的心房右到左的通路是中风的可能病因。
首先，需要利用经胸廓的对比超声心电图是进行血管当中的气泡进行比对。
检查步骤为，将盐水通过周围静脉套管注射（理想地放置在下半身，但左腹前窝通常是一个更现实的选择），病人需要进行咽鼓管充气检查法或者打喷嚏。
在存在心脏分流（右到左）的情况下，在气泡到达右心房后的三到四个心周期内，心脏左侧应出现气泡。
而之后再在左心出现的气泡可能反映了肺分流。
需要由一名经验丰富的操作员来进行操作上述步骤。
并且需要多次进行重复的步骤来进行确诊。
图1显示了从右向左传输的气泡的确诊情况
经颅多普勒是对比超声心动图的无创口替代品。
它是一种评估从右到左分流的可靠检测方法，但是这个方法无法体现PFO的解剖结构。

对病因无法确认的中风患者进行对比超声心电图或者是颅内多普勒之后，确诊存在血管内气泡的情况下需要再次进行经食管超声心动图(TOE)。
TOE可以进一步的帮助医生确诊血管气泡。
这样可以帮助结构性心脏团队能够准确地确定PFO的解剖结构。
对PFO的评估如图1所示。
TOE还可以排除其他可能存在的分流情况，如室间隔缺损、肺静脉引流异常或鼻窦静脉缺损。
使用TOE对PFO进行详细评估不属于本文范围。

需要多个专业专家（包括中风医生或神经学家、心脏成像专家、放射科医生和介入心脏病专家）参与针对PFO导致的中风的诊断和治疗决策制定。
病因的审查应在多学科讨论情况下进行考虑，并全面对患者进行管理。

*** PFO 封闭流程

在许多医疗中心，可作为日间病例程序实施PFO闭合术。
该手术可在配备使用透视指导和生理监测的标准导管室进行。
接受此手术的患者将降低长期中风风险，但该手术不会立即缓解当前的症状。
因此，应采取所有可能的措施来减少并发症。

作者认为，该手术应该尽可能没有并发症，因为即使是小的并发症，都将会将该手术相对于常规最优治疗的优势中和掉。
超声引导的股骨静脉通路，超声心动图指导、适当的抗凝治疗和特别的护理，对于减少空气阻塞和巩固PFO封闭术的治疗结果都很重要。

TOE以及心内超声心动图监测都是必须要进行的。目前在英国这样的检查是强制的，并且2019心血管造影协会也推荐了这样的检查流程。

虽然这个手术可以由非常有经验的操作人员用透视镜检查来独立进行操作，但超声心动图可以帮助评估房间隔的解剖结构，直接可视化PFO闭合装置位置，以及装置释放前与主动脉瓣和二尖瓣相对位置关系。
一般需要全身麻醉来实施TOE，这可能会增加手术的成本和长度。

该手术从股静脉开始，并利用超声引导穿刺。
应给予足够的抗凝剂（未分离的肝素80-100IU/kg）。
6-Fr多功能诊断导管和0.035 J型尖导丝用于穿过PFO并进入肺静脉（通常为左上肺静脉）。
然后，它可以换成一根硬导线，以帮助囊体的运送。
对PFO的大小测量需要在导线穿过前后进行两次测量，因为相关操作可能会导致PFO气孔的变大或者变小。
三维成像软件可用于确定左右心房的最大开口和最小长度。
调整PFO的开口（Balloon sizing of the PFO）一般是不要求的，但是也可以利用定量的血管造影工具，TOE和心内心电图进行确认。
左前斜颅透视投影可能有助于这一点，由于这个投影结构是可以看到心房隔膜的。
将会使用符合要求的囊体进行操作，但是囊体（bulloon sizing，是测量缺陷孔大小的一种方法）还是将扩大PFO并且缩短PFO的通路。
如果PFO的通路比较长，那么将PFO通路缩短就是适当的操作，但是这样的可能会增加PFO的尺寸，需要更大的设备来处理。
PFO隧道长度过长、房间隔动脉瘤或者是男性患者这类因素都可能要求使用更加大的设备进行闭合。
对PFO测量的精确度有选择合适的设备来确定。

当PFO的大小测量结束了，通过输送鞘适当大小的设备可通过PFO进入左心房。之后设备的左右面的盘体分别展开。
需要确保整个手术中输送鞘保持干燥，来降低空气或血栓栓塞的风险。
装置展开后，需要通过超声心动图和透视检查确认装置的位置。
如果设备释放后位置存在偏差，可以使用gooseneck snare项圈来恢复设备。PFO封闭术所涉及的步骤如图2所示。

在设备部署后进行抗血小板治疗的相关实验结果仍不完整。
由PFO闭合设备导致血栓是，术后可能会出现的严重并发症。
在实践中，阿司匹林和氯吡格雷通常需要患者服用6个月，但是这样的做法没有具体的评价实验进行支持。
在针对PFO的评估实验当中，早期停止双重抗血小板治疗与轻微脑血管症状的发生率的增加相关。
长期的观察研究表明，这是一种安全的治疗手段。

一些手术医生会让患者使用抗血小板药物，需要重申的是，这样做没有明显的理论和实践结果支撑。
单次抗血小板治疗(通常每天氯吡格雷75毫克)需要无限期持续，因为该装置可能需要5年才能内皮化。
欧洲经皮心血管介入协会的共识声明目前建议采用这种方法。

随访是非常重要的，但是具体的随访时间还是不确定的
由于大多数设备在大约6个月的时间可以完成内皮化，因此，在该阶段可以考虑重复囊体检查。
当因为职业的需要进行PFO闭合手术的时候，随访的时间安排比较重要。

*** PFO 闭合设备

目前上市了很多大小形状不同的闭合设备。
大部分都已经获得了欧盟的CE标识，但是美国需要随机评估实验来证明其有效性，只有很少的设备获得了FDA的批准。
大多数设备都是由短腰连接双盘设计。
Gore闭合器以及Amplatzer闭合器是目前市面上最常见的两种设备，如图3。
Gore闭合器是由覆盖着膨胀的聚四氟乙烯的五根镍钛诺合金构成。
早期的临床经验表明，它是一种多功能器械，易于部署、高手术成功率和低并发症率。
Amplatzer闭合器同样也是一种镍钛诺合金制作而成的，该装置在随机临床试验中最常用。
因此有很多临床的数据来证明他的有效性。
还有很多其他的商业设备可以使用，包括 Occlutech PFO 闭合器，Ultraspet (Cardia)，加上一些心脏缝合设备。

** Future Directions

关于PFO闭合术，有一些研究问题还没有得到解决。
针对复发性中风风险以及发生血栓与抗出血的风险的情况下，最优的抗血小板以及抗凝治疗方法。
当前的指导方针是基于共识声明和上文中提及的临床试验中所采用的策略。
没有相关的分析研究表明，在中风后PFO未关闭的情况下，对抗凝有任何明显的额外益处。
进一步评估抗凝疗效和双抗血小板治疗最佳持续时间的研究是值得推进的方向。
使用非创性超声心动图简化手术可能是一个简化手术的方向，但是在协会的一致声明中不建议使用。
一项建立研究经胸超声心动图支持的透视方法的安全性和有效性的临床试验目前正在进行中。

在发生中风之前，对PFO可能引发中风的风险进行预先判断依旧是一个golden ticket。
有一些研究构建了一个针对高风险的PFO的一个评分系统，但是目前还没有任何在中风发作之前的判定成功的例子，因为PFO通常是静默的。
患有PFO的遗传性血友病患者可能是预防性接受PFO闭合手术的候选者。
观察性研究表明，组内那些接受PFO闭合术的人有着更低的中风或短暂性缺血发作的发生率。
需要随机试验来评估该组是否会受益，但鉴于该组的患者数量相对较少，招募更多的患者进入实验是非常有挑战的工作。

最近一项对手术患者的观察性研究发现，PFO患者中缺血性卒中的发生率显著更高。
对于接受双重抗血小板治疗或抗凝治疗的患者以及接受了PFO闭合手术的患者而言，缺血性卒中的发生的风险更低了。
这些观察数据是假设产生的，但表明可能有一些人可以从前期PFO闭合中获益，但需要进一步精心设计的临床试验来证明这一点，以对抗程序性的风险。

此外只有有限的数据来支撑亚组在治疗方面的差异。
对实验报告按照性别进行结果展示分析发现男性中风数量显著减少，女性中风数量也无显著减少。
在这些研究中接受治疗的大多数患者都是男性。需要进一步的工作，以确定这些群体中是否有有意义的差异。同样，也可以检查少数民族之间的差异。

最后，扩大到其他适应症，特别是针对缓解偏头痛，需要更多更加高质量证据来进行支撑。
心脏间隔闭合器-偏头痛临床研究是一项2020年开始，针对PFO缓解偏头痛和虚假对照组的试验。
安慰组虚假的手术对于鉴别与偏头痛研究相关的强安慰剂效应十分重要。

** Conclusion

本文中讨论了PFO可能适应的多种症状，包括，病因不明的中风，反向的系统性血栓，减压病以及缺氧综合征，并给出了相关的证据进行阐述。
本手术所需的技能需在经验丰富的介入心脏病专家帮助下进行学习。
需要注意手术当中的各种细节，减少PFO闭合术的并发症是这一项手术的关键。
